name: Structurizr Lite Export Workflow
on:
  push:
    paths:
      - 'docs/*.dsl'
      - 'docs/**/*.dsl' 
jobs:
  export-diagrams:
    runs-on: ubuntu-latest
    services:
      structurizr:
        image: structurizr/lite:latest
        ports:
          - 8080:8080
        options: --network-alias structurizr
    steps:
      - name: Adjust workspace permissions
        run: |
          sudo chmod -R u+rwx ${{ github.workspace }} || true
          sudo chown -R $USER:$USER ${{ github.workspace }} || true
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          clean: true
      - name: Copy workspace files to Structurizr Lite
        run: |
          CONTAINER_ID=$(docker ps --filter "name=structurizr" --format "{{.ID}}")
          docker cp ${{ github.workspace }}/docs/workspace.dsl $CONTAINER_ID:/usr/local/structurizr/workspace.dsl
          docker cp ${{ github.workspace }}/docs/styles.dsl $CONTAINER_ID:/usr/local/structurizr/styles.dsl
          docker cp ${{ github.workspace }}/docs/workspace.json $CONTAINER_ID:/usr/local/structurizr/workspace.json
          docker cp ${{ github.workspace }}/docs/.structurizr $CONTAINER_ID:/usr/local/structurizr/.structurizr
          CONTAINER_ID=$(docker ps --filter "name=structurizr" --format "{{.ID}}")
          docker exec $CONTAINER_ID ls -la /usr/local/structurizr/
      - name: Inspect Directory Structure
        run: |
          echo "Listing root directory contents:"
          ls -la /
          echo "Listing GitHub workspace contents:"
          ls -la ${{ github.workspace }}
          echo "Listing Action-specific folder contents:"
          ls -la /home/runner/work/_actions
          ls -la /home/runner/work/_actions/vitormartins1/structurizr-lite-puppeteer-integration-action/
          ls -la /home/runner/work/_actions/vitormartins1/structurizr-lite-puppeteer-integration-action/v1.0.18/
      - name: Export Structurizr Diagrams
        uses: vitormartins1/structurizr-lite-puppeteer-integration-action@v1.0.18
        with:
          structurizr_url: 'http://localhost:8080/workspace/diagrams'
          format: 'png'
          output_dir: '${{ github.workspace }}/docs/diagrams/'
      - name: List Generated Diagrams
        run: ls -la ${{ github.workspace }}/docs/diagrams
      - name: Upload Diagrams
        uses: actions/upload-artifact@v4
        with:
          name: structurizr-diagrams
          path: ${{ github.workspace }}/docs/diagrams/
      - name: Commit Generated Diagrams
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          cd ${{ github.workspace }}
          git add docs/diagrams/
          git commit -m "Atualizando diagramas gerados automaticamente"
          git push origin ${{ github.ref_name }}